# Generated by Django 5.0.7 on 2024-07-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_list_model',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo_work', models.TextField(max_length=250)),
                ('todo_create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
