# Generated by Django 5.0.7 on 2024-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list_model',
            name='todo_create_time',
        ),
        migrations.RemoveField(
            model_name='todo_list_model',
            name='todo_id',
        ),
        migrations.RemoveField(
            model_name='todo_list_model',
            name='todo_work',
        ),
        migrations.AddField(
            model_name='todo_list_model',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo_list_model',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todo_list_model',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo_list_model',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
