# Generated by Django 5.0.7 on 2024-07-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_list_model_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list_model',
            name='user',
        ),
    ]
